#!/usr/bin/python
# -*- coding: utf-8 -*-

possibleLanguages = {"Afar" : "a",
             "Abkhazian" : "ab",
    "Afrikaans" : "af",
    "Akan" : "ak",
    "Albanian" : "sq",
    "Amharic" : "am",
    "Arabic" : "ar",
    "Aragonese" : "an",
    "Armenian" : "hy",
    "Assamese" : "as",
    "Avaric" : "av",
    "Avestan" : "ae",
    "Aymara" : "ay",
    "Azerbaijani" : "az",
    "Bashkir" : "ba",
    "Bambara" : "bm",
    "Basque" : "eu",
    "Belarusian" : "be",
    "Bengali" : "bn",
    "Bihari" : "bh",
    "Bislama" : "bi",
    "Tibetan" : "bo",
    "Bosnian" : "bs",
    "Breton" : "br",
    "Bulgarian" : "bg",
    "Burmese" : "my",
    "Catalan" : "ca",
    "Valencian" : "ca",
    "Czech" : "cs",
    "Chamorro" : "ch",
    "Chechen" : "ce",
    "Chinese" : "zh",
    "Church Slavic" : "cu", 
    "Old Slavonic" : "cu",
    "Church Slavonic" : "cu",
    "Old Bulgarian" : "cu", 
    "Old Church Slavonic" : "cu",
    "Chuvash" : "cv",
    "Cornish" : "kw",
    "Corsican" : "co",
    "Cree" : "cr",
    "Welsh" : "cy",
    "Czech" : "cs",
    "Danish" : "da",
    "German" : "de",
    "Divehi" : "dv", 
    "Dhivehi" : "dv",
    "Maldivian" : "dv",
    "Dutch" : "nl", 
    "Flemish" : "nl",
    "Dzongkha" : "dz",
    "Greek, Modern" : "el",
    "English" : "en",
    "Esperanto" : "eo",
    "Estonian" : "et",
    "Basque" : "eu",
    "Ewe" : "ee",
    "Faroese" : "fo",
    "Persian" : "fa",
    "Fijian" : "fj",
    "Finnish" : "fi",
    "French" : "fr",
    "Western Frisian" : "fy",
    "Fulah" : "ff",
    "Georgian" : "ka",
    "German" : "de",
    "Gaelic" : "gd",
    "Scottish Gaelic" : "gd",
    "Irish" : "ga",
    "Galician" : "gl",
    "Manx" : "gv",
    "Guarani" : "gn",
    "Gujarati" : "gu",
    "Haitian" : "ht",
    "Haitian Creole" : "ht",
    "Hausa" : "ha",
    "Hebrew" : "he",
    "Herero" : "hz",
    "Hindi" : "hi",
    "Hiri Motu" : "ho",
    "Croatian" : "hr",
    "Hungarian" : "hu",
    "Armenian" : "hy",
    "Igbo" : "ig",
    "Icelandic" : "is",
    "Ido" : "io",
    "Sichuan Yi" : "ii",
    "Inuktitut" : "iu",
    "Interlingue" : "ie",
    "Interlingua" : "ia",
    "Indonesian" : "id",
    "Inupiaq" : "ik",
    "Icelandic" : "is",
    "Italian" : "it",
    "Javanese" : "jv",
    "Japanese" : "ja",
    "Kalaallisut" : "kl", 
    "Greenlandic" : "kl",
    "Kannada" : "kn",
    "Kashmiri" : "ks",
    "Georgian" : "ka",
    "Kanuri" : "kr",
    "Kazakh" : "kk",
    "Central Khmer" : "km",
    "Kikuyu; Gikuyu" : "ki",
    "Kinyarwanda" : "rw",
    "Kirghiz; Kyrgyz" : "ky",
    "Komi" : "kv",
    "Kongo" : "kg",
    "Korean" : "ko",
    "Kuanyama" : "kj", 
    "Kwanyama" : "kj",
    "Kurdish" : "ku",
    "Lao" : "lo",
    "Latin" : "la",
    "Latvian" : "lv", 
    "Limburgan" : "li",
    "Limburger" : "li",
    "Limburgish" : "li",
    "Lingala" : "ln",
    "Lithuanian" : "lt",
    "Luxembourgish" : "lb",
    "Letzeburgesch" : "lb",
    "Luba-Katanga" : "lu",
    "Ganda" : "lg",
    "Macedonian" : "mk",
    "Marshallese" : "mh",
    "Malayalam" : "ml",
    "Maori" : "mi",
    "Marathi" : "mr",
    "Malay" : "ms",
    "Macedonian" : "mk",
    "Malagasy" : "mg",
    "Maltese" : "mt",
    "Moldavian" : "mo",
    "Mongolian" : "mn",
    "Maori" : "mi",
    "Malay" : "ms",
    "Burmese" : "my",
    "Nauru" : "na",
    "Navajo" : "nv",
    "Navaho" : "nv",
    "Ndebele, South" : "nr",
    "South Ndebele" : "nr",
    "Ndebele, North" : "nd", 
    "North Ndebele" : "nd",
    "Ndonga" : "ng",
    "Nepali" : "ne",
    "Dutch" : "nl",
    "Flemish" : "nl",
    "Norwegian Nynorsk; Nynorsk, Norwegian" : "nn",
    "Norwegian" : "no",
    "Chichewa" : "ny",
    "Chewa" : "ny",
    "Nyanja" : "ny",
    "Ojibwa" : "oj",
    "Oriya" : "or",
    "Oromo" : "om",
    "Ossetian; Ossetic" : "os",
    "Panjabi; Punjabi" : "pa",
    "Persian" : "fa",
    "Pali" : "pi",
    "Polish" : "pl",
    "Portuguese" : "pt",
    "Pushto" : "ps",
    "Quechua" : "qu",
    "Romansh" : "rm",
    "Romanian" : "ro",
    "Romanian" : "ro",
    "Rundi" : "rn",
    "Russian" : "ru",
    "Sango" : "sg",
    "Sanskrit" : "sa",
    "Serbian" : "sr",
    "Croatian" : "hr",
    "Sinhala; Sinhalese" : "si",
    "Slovak" : "sk",
    "Slovenian" : "sl",
    "Northern Sami" : "se",
    "Samoan" : "sm",
    "Shona" : "sn",
    "Sindhi" : "sd",
    "Somali" : "so",
    "Sotho, Southern" : "st",
    "Spanish; Castilian" : "es",
    "Albanian" : "sq",
    "Sardinian" : "sc",
    "Serbian" : "sr",
    "Swati" : "ss",
    "Sundanese" : "su",
    "Swahili" : "sw",
    "Swedish" : "sv",
    "Tahitian" : "ty",
    "Tamil" : "ta",
    "Tatar" : "tt",
    "Telugu" : "te",
    "Tajik" : "tg",
    "Tagalog" : "tl",
    "Thai" : "th",
    "Tibetan" : "bo",
    "Tigrinya" : "ti",
    "Tonga (Tonga Islands)" : "to",
    "Tswana" : "tn",
    "Tsonga" : "ts",
    "Turkmen" : "tk",
    "Turkish" : "tr",
    "Twi" : "tw",
    "Uighur; Uyghur" : "ug",
    "Ukrainian" : "uk",
    "Urdu" : "ur",
    "Uzbek" : "uz",
    "Venda" : "ve",
    "Vietnamese" : "vi",
    "Welsh" : "cy",
    "Walloon" : "wa",
    "Wolof" : "wo",
    "Xhosa" : "xh",
    "Yiddish" : "yi",
    "Yoruba" : "yo",
    "Zhuang; Chuang" : "za",
    "Chinese" : "zh","Zulu" : "zu"
    }