# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

import wx.html2 as theView

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDIALOG1(wx.Dialog):
#!XRCED:begin-block:xrcDIALOG1.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDIALOG1.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIALOG1")
        self.PostCreate(pre)

        self.ProjectName = xrc.XRCCTRL(self, "ProjectName")
        self.WebView = xrc.XRCCTRL(self, "WebView")
        self.Help = xrc.XRCCTRL(self, "Help")
        self.Ok = xrc.XRCCTRL(self, "Ok")
        self.Cancel = xrc.XRCCTRL(self, "Cancel")

        self.wv = theView.WebView.New(self)
          
        self.selectedURL = None
        
        self.Sizer.Replace(self.WebView, self.wv)
        self.Sizer.Layout()
        self.Refresh()
        
        self.Bind(theView.EVT_WEB_VIEW_NAVIGATING, self.onWebViewNavigating, self.wv)
    
    
    def loadTemplates(self):
        
        self.wv.LoadURL("file:///Users/maker/Desktop/test.html")
        
    def onWebViewNavigating(self, evt):
        self.selectedURL = evt.GetURL()


# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    makerTemplateDialog_xrc = '''\
<?xml version="1.0" ?><resource class="wxHtmlWindow">
  <object class="wxDialog" name="DIALOG1">
    <object class="wxBoxSizer">
      <object class="sizeritem">
        <object class="wxPanel">
          <object class="wxStaticText">
            <pos>10, 10</pos>
            <label>Project name:</label>
          </object>
          <object class="wxTextCtrl" name="ProjectName">
            <pos>10, 35</pos>
            <size>680, 20</size>
            <value>New Project Name</value>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <size>700, 70</size>
        </object>
        <option>0</option>
        <flag>wxEXPAND|wxGROW</flag>
        <border>1</border>
      </object>
      <object class="sizeritem">
        <object class="wxHtmlWindow" name="WebView">
          <pos>10, 10</pos>
          <size>320, 240</size>
          <style>wxBORDER_RAISED</style>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <option>1</option>
        <flag>wxEXPAND|wxGROW|wxADJUST_MINSIZE|wxFIXED_MINSIZE</flag>
        <minsize>700, 500</minsize>
      </object>
      <object class="sizeritem">
        <object class="wxPanel" name="BottomPanel">
          <object class="wxButton" name="Help">
            <pos>10, 10</pos>
            <label>Help</label>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <size>700, 50</size>
          <object class="wxButton" name="Ok">
            <pos>600, 10</pos>
            <label>Ok</label>
            <default>1</default>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <object class="wxButton" name="Cancel">
            <pos>500, 10</pos>
            <label>Cancel</label>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
        </object>
      </object>
      <orient>wxVERTICAL</orient>
      <XRCED>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <pos>10, 10</pos>
    <size>700, 500</size>
    <title>Create new project</title>
    <centered>1</centered>
    <focused>1</focused>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/makerTemplateDialog/makerTemplateDialog_xrc', makerTemplateDialog_xrc)
    __res.Load('memory:XRC/makerTemplateDialog/makerTemplateDialog_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Project name:")
    _("New Project Name")
    _("Help")
    _("Ok")
    _("Cancel")
    _("Create new project")

