# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcDIALOG1(wx.Dialog):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIALOG1")
        self.PostCreate(pre)

        # create attributes for the named items in this container
        self.List = xrc.XRCCTRL(self, "List")
        self.Preview = xrc.XRCCTRL(self, "Preview")
        self.Ok = xrc.XRCCTRL(self, "Ok")
        self.Cancel = xrc.XRCCTRL(self, "Cancel")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    makerTemplateDialog_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="DIALOG1">
    <title>select a template</title>
    <centered>1</centered>
    <pos>0,0</pos>
    <size>640, 320</size>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxHORIZONTAL</orient>
          <object class="sizeritem">
            <object class="wxListBox" name="List">
              <content/>
            </object>
            <option>1</option>
            <flag>wxEXPAND|wxGROW</flag>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBitmap" name="Preview">
              <bitmap stock_id="wx.NULLBITMAP"/>
              <size>320, 240</size>
              <style>wxSIMPLE_BORDER</style>
            </object>
            <option>0</option>
            <flag>wxEXPAND</flag>
            <minsize>322, 260</minsize>
          </object>
        </object>
        <option>1</option>
        <flag>wxEXPAND|wxGROW</flag>
      </object>
      <object class="sizeritem">
        <object class="wxPanel">
          <object class="wxButton" name="Ok">
            <label>OK</label>
            <default>1</default>
            <pos>540, 0</pos>
            <size>80, 30</size>
          </object>
          <object class="wxButton" name="Cancel">
            <label>Cancel</label>
            <default>0</default>
            <pos>450, 0</pos>
            <size>80, 30</size>
          </object>
        </object>
        <option>0</option>
        <flag>wxEXPAND</flag>
        <minsize>640, 40</minsize>
      </object>
    </object>
    <exstyle/>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/makerTemplateDialog/makerTemplateDialog_xrc', makerTemplateDialog_xrc)
    __res.Load('memory:XRC/makerTemplateDialog/makerTemplateDialog_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("select a template")
    _("OK")
    _("Cancel")

